### PR TITLE
Subject spiders

### PR DESCRIPTION
**Pull request by damonms**
This one is almost ready to go. I just wanted to track one thing that needs to be resolved before we merge this in. Basically in launcher in build_project, how do we want to handle the last_modified date?

The issue is that if we set the last updated date after updating the subject, it will set the last_updated timestamp for the earliest session. This raises the problem that this first session will never be updated unless run manually. Should we set the last_modified date at the subject level instead?

If we ignore it entirely, the issue is that we have a large overhead of it iterating every subject before getting to the first session.

Thoughts?

### CODE REVIEW

**Comment by byvernault** [comment]
Hey Steve,

We decided to put the last update timestamp to the Session because we realised with Brian that accessing the subject and set the date takes more time than the session. 

I am not quite sure what his the issue with the first session update? 

For the subject Spider, the issue is that we don't loop through the subjects but the sessions directly. So probably, we will have to run after it the spider on the subject in a second loop. 

Are the Subject spider for longitudinal studies? Where are you storing the results?

Cheers,

Ben

**Comment by byvernault** [comment]
Oh I see what you mean now with the first session.

We might want to discuss with XNAT about having an assessors on a subject level instead of session. It will organise the data in a better way. 

For the first session, how do you know which session is the first one? One thing we could do if we keep the assessor at a session level, we could have a second loop after looping through all the sessions and filter them to keep only the subject processors and update the processors. 

Brian, thoughts?

Ben

**Comment by byvernault** [comment]
We could maybe add a type of session that will be longitudinal and this session will hold all the assessors for longitudinal processors for a subject. 

If you extend this to the next level, we could do the same for a project, create a new subject type that will be for subjects analysis and this subject will have a session for each analysis you do and then assessors.
E.G: cross subjects between subject 1/2/3 --> session in this subject with either the label containing those information or some variables. 

Just an idea.

Ben

**Comment by damonms** [comment]
Hi Ben,

You might not have seen the method, but the sessions are date sorted. There are several conveniece methods to throw away sessions without dates. Hence, we should always know what the first session is. If none of the sessions are dated, then you can get an empty list of sessions and set NO_DATA in the processor. 

As far as adding a secondary loop, I'm not sure that we should do this. We already have one of these and it adds ~15 seconds to dax_build every session. 

I'm not opposed to storing the assessor at the subject level, and had oridingally implemented it this way but thought it might further complicate things on the user's end. Additionally, since we have never hopped in that boat yet, I tried to keep with what is know to work. It would be a fairly trivial change to test this.

Either way, I stil strongly vote that we use something similar to this implementation, rather than hacking a subject/session or some combination of the two for longitudinal processing. 

I wrote this thinking about project processors as well and I'm not sure we even want to cross that river. Realistic walltime and memory allocation, along with the likely event of a failure to download during the spider are a bit worrisome. Maybe these types of things are best suited for offline analysis and then uploaded separately?

Steve

**Comment by damonms** [comment]
Pending update to XNAT this Friday to see if the pyxnat set issue is resolved. Will follow up with details

**Comment by damonms** [comment]
Major roadblock. Pyxnat doesn't support assessors on subjects

**Comment by bud42** [comment]
Noooooo!

**Comment by damonms** [comment]
So, even though you *can* upload it, it's not even supported in the REST hierarchy of XNAT and thus I think we're heading down a pretty large hack to get it working. Maybe we make a request on the forum to support this later on? I kind of feel like this is dead at this point unfortunately.

**Pull request closed without merging**
