### PR TITLE
Added urllib and quoted the filename

### PR DESCRIPTION
**Pull request by KarthikMasi**

### CODE REVIEW

**Comment by KarthikMasi** [comment]
This was much easier than fixing pyxnat. I just had to do some research on quoting escape characters with % for requests.

**Comment by baxpr** [comment]
Ahahaha perfect, thanks!

**Comment by baxpr** [comment]
Working for me!

**Comment by baxpr** [comment]
@KarthikMasi looks like we need a similar fix for Xnatupload

```
  + 10/14 objects: scan 5354 -- type: [BR-DY_CTAC] Brain Dynamic -- series description: [BR-DY_CTAC] Brain Dynamic -- quality: questionable
   > Resource NIFTI
Traceback (most recent call last):
  File "/Users/rogersbp/miniconda3/envs/dax-2.2/bin/Xnatupload", line 860, in <module>
    run_xnat_upload, extra_display=extra_display)
  File "/Users/rogersbp/miniconda3/envs/dax-2.2/lib/python3.6/site-packages/dax/xnat_tools_utils.py", line 182, in run_tool
    run_tool_fct(args)
  File "/Users/rogersbp/miniconda3/envs/dax-2.2/bin/Xnatupload", line 819, in run_xnat_upload
    upload_data_xnat(xnat, args, scans, assessors)
  File "/Users/rogersbp/miniconda3/envs/dax-2.2/bin/Xnatupload", line 651, in upload_data_xnat
    upload_resources(xnat_obj, args, xnat_obj, obj)
  File "/Users/rogersbp/miniconda3/envs/dax-2.2/bin/Xnatupload", line 689, in upload_resources
    extract=not args.no_extract)
  File "/Users/rogersbp/miniconda3/envs/dax-2.2/bin/Xnatupload", line 705, in upload_path
    isfile, fpath = is_file(fpath)
  File "/Users/rogersbp/miniconda3/envs/dax-2.2/bin/Xnatupload", line 495, in is_file
    if len(glob.glob(os.path.join(fpath, '*'))) == 1  \
  File "/Users/rogersbp/miniconda3/envs/dax-2.2/lib/python3.6/glob.py", line 20, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/Users/rogersbp/miniconda3/envs/dax-2.2/lib/python3.6/glob.py", line 71, in _iglob
    for dirname in dirs:
  File "/Users/rogersbp/miniconda3/envs/dax-2.2/lib/python3.6/glob.py", line 71, in _iglob
    for dirname in dirs:
  File "/Users/rogersbp/miniconda3/envs/dax-2.2/lib/python3.6/glob.py", line 72, in _iglob
    for name in glob_in_dir(dirname, basename, dironly):
  File "/Users/rogersbp/miniconda3/envs/dax-2.2/lib/python3.6/glob.py", line 83, in _glob1
    return fnmatch.filter(names, pattern)
  File "/Users/rogersbp/miniconda3/envs/dax-2.2/lib/python3.6/fnmatch.py", line 52, in filter
    match = _compile_pattern(pat)
  File "/Users/rogersbp/miniconda3/envs/dax-2.2/lib/python3.6/fnmatch.py", line 46, in _compile_pattern
    return re.compile(res).match
  File "/Users/rogersbp/miniconda3/envs/dax-2.2/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/Users/rogersbp/miniconda3/envs/dax-2.2/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Users/rogersbp/miniconda3/envs/dax-2.2/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/Users/rogersbp/miniconda3/envs/dax-2.2/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/Users/rogersbp/miniconda3/envs/dax-2.2/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/Users/rogersbp/miniconda3/envs/dax-2.2/lib/python3.6/sre_parse.py", line 765, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/Users/rogersbp/miniconda3/envs/dax-2.2/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/Users/rogersbp/miniconda3/envs/dax-2.2/lib/python3.6/sre_parse.py", line 553, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
sre_constants.error: bad character range R-D at position 15
```

**Comment by baxpr** [comment]
Here is the csv line:

```
scan,ROGERSTEST,141185,PET,801521,5354,[BR-DY_CTAC] Brain Dynamic,[BR-DY_CTAC] Brain Dynamic,questionable,NIFTI,/path/to/NIFTI
```

**Comment by KarthikMasi** [comment]
Thanks Baxter! Will apply the fix.

**Review by baxpr — APPROVED** [review]
Works for me. @bud42 I think it's ready to merge

**Comment by bud42** [comment]
Thanks!

**Pull request merged**
