### PR TITLE
Yaml settings

### PR DESCRIPTION
**Pull request by byvernault**
Hi team,

I added a lot of new stuff in this branch. See below for details. As always, feel free to contact me for question or any remarks.

News:
    1) adding the yaml settings format: instead of creating a .py, you can use a YAML format for your projects settings. I will upload a wiki page next week on how to generate one.
    2) futurizing the package dax. I used futurize --stage1 and 2 on dax to allow the package to work with python 2 and 3. I haven't got time to test it yet on python 3 but it should by theory be working.
    3) Adding the format Yaml for the upload settings as well when you have several xnat instances. You can specify to which host you upload a project.
    4) Possibility to edit the fields in an auto processor by giving the path of the attributes to changes: e.g: auto_proc = AutoProcessor('/.../proc.yaml', user_inputs={'inputs.xnat.scans.scan1.types': 'T1,MPRAGE,T2')

Bugs:
   1) I added a line when catching exceptions with dax executable to remove the flagfile after printing the exception. In this case, we should have less flagfiles that exist even when the process isn't running.
   2) for dax_generator, I set by default to use the getcwd directory if not specify. Before, it was None.

Kind Regards,
Ben

### CODE REVIEW

**Comment by bud42** [comment]
oh sure, fix it now.

**Comment by bud42** [comment]
@byvernault it doesn't like my modules. are yours loading correctly?

**Comment by byvernault** [comment]
Yes, what do you have?

Sorry, few commits while I am testing it more on my cluster on different projects.

**Comment by bud42** [comment]
working now. way cool!

**Pull request merged**
