### PR TITLE
Create XnatShareSession

### PR DESCRIPTION
**Pull request by duettwe**
NOT DONE

Right now I'm just getting this to actually work with a test, then I'll go in and make it like the other tools.

### CODE REVIEW

**Comment by duettwe** [comment]
This almost works. It shares into the VUIIS_ABCD project, BUT it shares the ACCESSION NUMBER rather than the subject/experiment.

For instance, VUIISXNAT04_S17846 instead of 212533 for the subject and VUIISXNAT04_E232899 instead of 212533 for the experiment.

When I go into the subject, I also do not see any scans or experiments listed, but when I click delete, they are listed as something that can be deleted.

**Comment by baxpr** [comment]
subj_str should be subj.label and similar for exp_str. Something along those lines

**Comment by duettwe** [comment]
So this works, but there's some issues:
1. Only shares MR Session Experiments
2. Requires csv in Xnatdownload format (download_report.csv)
3. Doesn't accept subjects/sessions/experiments as input
4. Doesn't pad when there are sessions like '001' (VUIIS_ABCD); this would end up being just '1'

I'd like to fix all of these, but this does work, it's just a pain.

I'm also going to change all the print statements to LOGGER so it looks better.

**Comment by baxpr** [comment]
1 is ok for now but eventually would also like to handle PET

2-3 goal would be to supply a source project, list of sessions, and destination project. First two could come from any csv if you read in with pandas

4 Sounds like just need to read in csv as string not numeric. Can force this with dtype=str in pandas.read_csv

**Comment by duettwe** [comment]
I think I have a way to fix all of these. The easiest way to fix 1-3 is that Xnatdownload is used. I can scrape experiment type (MR, CT, PET, HD) from there. Obviously can get project/sessions/subjects from that. Only would have to ask for destination.

This would require users to open the csv and remove what they didn't want though, or specify exactly what they want through Xnatdownload.

**Comment by baxpr** [comment]
Work from an Xnatreport instead of Xnatdownload

**Comment by duettwe** [comment]
Do I need to do some sort of lockfile? Similar to what you did with the NIRS project sharing?

**Comment by baxpr** [comment]
No - lockfile was for some other reason iirc

**Comment by duettwe** [comment]
I also need to set it up where it grabs the sending project from the csv if it's not provided.

**Comment by duettwe** [comment]
If you guys want to give this a go. Let me know what needs to be changed and what not. It can use the output of Xnatreport csv as the --csv file. It's also REALLY slow, so if you have any ideas there too, that'd be great.

Also, I'm not sure how to make this work where it's just
```
XnatShareSession --to PID --csv XXX.csv
```
Right now I have to do the `./` in front.

**Comment by baxpr** [comment]
Suggest refering to "source" and "destination" project throughout, and name vars as `src_whatever` and `dest_whatever` - will help clarity a lot

**Comment by baxpr** [comment]
best practice - if possible put all xnat operations together in a

```
with pyxnat.Interface() as XNAT:
```

**Comment by duettwe** [comment]
> Suggest refering to "source" and "destination" project throughout, and name vars as `src_whatever` and `dest_whatever` - will help clarity a lot

This is done. Let me know if you see any more.



> best practice - if possible put all xnat operations together in a
> 
> ```
> with pyxnat.Interface() as XNAT:
> ```
> 
> I think Interface method will refer to XNAT_HOST env var and .netrc when no options are given
> 
> ... example:
> 
> https://github.com/VUIIS/dax/blob/5045c8de2eeab6418c95e0a42ea2cf5c0d515708/bin/Xnat_tools/Xnatsetvar#L94

Working on this.

**Comment by duettwe** [comment]
> best practice - if possible put all xnat operations together in a
> 
> ```
> with pyxnat.Interface() as XNAT:
> ```
> 
> I think Interface method will refer to XNAT_HOST env var and .netrc when no options are given
> 
> ... example:
> 
> https://github.com/VUIIS/dax/blob/5045c8de2eeab6418c95e0a42ea2cf5c0d515708/bin/Xnat_tools/Xnatsetvar#L94

You no longer have to type your password. 

This is giving me an 'read operation timed out' errors for every subject shared, but not the experiments. Not sure what's going on there yet. They do all end up getting shared though.

**Comment by duettwe** [comment]
Maybe that was just that particular project or something. This is working as expected on another test.

**Pull request merged**
