### PR TITLE
Modify is_bad_qa to actually find bad qa

### LINKED ISSUE #68: Reproc and "Bad (Needs Edits)" show up as a good cassr
This is in dax 0.4.0 release. Just wanted to make sure it's actually fixed in the repo. If not. I'm going to apply a patch because it's broken for a project right now.

### PR DESCRIPTION
**Pull request by bud42**
resolve #68

### CODE REVIEW

**Comment by bud42** [comment]
@byvernault any thoughts?

**Comment by byvernault** [comment]
I will check tomorrow.

Ben

**Comment by byvernault** [comment]
I don't have any jobs yet using the QA of other jobs so I can't really test it. Did you get a chance to give it a try?

It looks good to me. It should do the jobs.

**Comment by damonms** [comment]
Works for the errors I had.

**Pull request merged**
