### PR TITLE
Dax setup reform

### PR DESCRIPTION
**Pull request by byvernault**
Hi guys,

This branch is a reform of the dax_setup and dax_settings. I tried to create a better version of the settings.

Features:
1) dax_setup will now ask you if you want to set/edit the settings. It will set it to a default template if you say no. It will ask you if you want to edit each section of the settings.

2) New section in the settings: code_path. You can now store the path for the spiders / processors / modules folder and from dax_settings object, you can call load_code_path() to load all the spiders/processors/modules.

3) I remove the redcap section to move the two options to dax_manager since there were linked.

4) I added to each executables in dax a check to the settings to see that everything is present to allow the executables to run.

5) A lambda user can now use any of the tools by just running dax_setup and say no to set the settings.

Let me know if you find any bug or if you have any question.

Cheers,

Ben

### CODE REVIEW

**Comment by bud42** [comment]
I still get a redcap section and I don't see a code_path section. You sure this has all your updates?

**Comment by bud42** [comment]
Wait, I see what happened: when I installed the branch, it copied in the default dax_settings.ini. Then when I used dax_setup I was editing this file which had a redcap section and didn't have a code_path section. 

We need to either not copy a default file or modify the default file to work with the new dax_setup.

**Comment by byvernault** [comment]
Yes indeed. It copies the default settings that isn't the good one. I forgot to edit it. If we edit it, we should be good then.

**Comment by byvernault** [comment]
I updated the default one.

**Comment by bud42** [comment]
Looks great! @damons ?

**Comment by bud42** [comment]
@damonms

**Comment by byvernault** [comment]
Just adding a method to the class spider to test executables given to the class. It will returns the version from the options --version if there is one. 

@damonms : Steve, what do you think about the branch and the new .dax_settings.ini. Let me know if you find any bug.

**Comment by byvernault** [comment]
Hi guys, 

I just added to this branch three functions in the spider class. One to generate a pdf page with images, one to generate pdf page with stats and one to merge pdf_pages. This will help people to generate a easy pdf with displaying images or stats all in python.

You can find the three functions in spiders.py.

Here is an example to call them:

# PDF path:
output_dir = '/Users/byvernault/data/pdf'
pdf_path = '/Users/byvernault/data/pdf/output.pdf'
image_file = '/Users/byvernault/data/pdf/output.nii'

print "--Page image--"
# fig = page
slices = {'0':[50, 80, 100, 130],
              '1':[150, 180, 200, 220]}
labels = {'0': 'Vessels first',
               '1': 'Vessels Second'}
cmaps = {'0':'hot',
         '1':'hot'}

vmins = {'0':0,
         '1':0}
vmaxs = {'0':100,
         '1':100}
images = [image_file, image_file]
plot_images_figure(pdf_path, 2, images, 'Vessel Extraction', labels,
                   slices=slices, cmap=cmaps, vmins=vmins, vmaxs=vmaxs)


For stats: 

pdf_path = '/Users/byvernault/data/pdf/output2.pdf'
volume = '/Users/byvernault/Downloads/20151203_14395801041532ChannelRoutinthoks005a1001_volumes.csv'
with open(volume, 'rb') as csvfileread:
    csvreader = csv.reader(csvfileread, delimiter=',')
    li_name = csvreader.next()
    li_volume = csvreader.next()

stats_dict = OrderedDict()
for index, name in enumerate(li_name):
    stats_dict[name] = li_volume[index]    

plot_stats_page(pdf_path, 2, stats_dict, 'Volume GIF')


and then to merge:

merge_pdf_pages(['/Users/byvernault/data/pdf/output.pdf', pdf_path], '/Users/byvernault/data/pdf/final.pdf')

Let me know what do you think.

The dax_setup is working great for me. 

Cheers,

Ben

**Comment by damonms** [comment]
Sounds good to me. Let's try and keep the scope of the PRs limited as best as possible to the title. 

Steve

**Pull request merged**
