### PR TITLE
Create dax-testrun.sh

### PR DESCRIPTION
**Pull request by duettwe**

### CODE REVIEW

**Comment by duettwe** [comment]
Moving from https://github.com/VUIIS/dax_local/pull/204

**Comment by duettwe** [comment]
This needs to be modified to handle multiple assessors.

**Comment by duettwe** [comment]
Or maybe just specify particular scans/assessors as inputs.

**Comment by baxpr** [comment]
This is working well enough as is to bring onto the main branch - @bud42 ?

**Review by bud42 — APPROVED** [review]
Cool!

**Pull request merged**
