### PR TITLE
Refactor dax settings

### PR DESCRIPTION
**Pull request by damonms**
OK. I think this one is finally ready for review. This is a complete refactor of the old dax_settings file. I left dax_settings.py in place, but it is now a class to contain dax_settings rather than being a script. dax_settings.ini is the new proposed replacement based on the INI format. I think this is very easily readable and is a lot sleeker than what we were previously using. 

I added convenience utility called dax_setup_handler.py which will build the dax_settings.ini file. 

I'll make a new branch to update the docs to explain what it all means. I tried to keep a 1:1 mapping between old naming and new naming. 

With respect to REDCap, I took a bit of a liberty and required (read: assumed) that anyone using this would use our standard template of the first instrument (which I don't think is a bad idea). I'm not sure we want to go down the rabbit hole of letting people define whatever variable names they want for such a small form. However, if there are objections, I will definitely fix. 

Since we don't have many installs, I haven't written a tool to transfer the old settings format to the new one, though this has been on my mind. Easy enough for me to write it up if there is a request for it. 

I just recently updated this to include Ben's commit for xsitype_include.

Best,
Steve

### CODE REVIEW

**Comment by damonms** [comment]
I should have mentioned, there is a new tool in dax_tools called dax_setup that runs dax_setup_handler.py.

**Comment by byvernault** [comment]
Hey Steve,

I checked this out yesterday and really liked it. I will look at it tomorrow in more details and give it a try.

Cheers,

Ben

**Comment by byvernault** [comment]
Steve,

I am testing your branch and the refactor of dax_settings. 
So if I understand well, you install the branch and then you run dax_setup. If you do that, it says:

ERROR: file /Users/byvernault/.dax_settings.ini not found
Please run dax_setup

I bet you must need to generate the .dax_settings.ini file or copy it from the dax folder. Right? Should dax_setup create this file?

I will test it out more and let you know what I found. I really like it.

Cheers,

Ben

**Comment by byvernault** [comment]
Line 227 in dax_settings.py, there is a typo error:

return self.get('admin', 'xsitpye_include').split(',')

it should be xsitype_include. :)

**Comment by byvernault** [comment]
It looks like as well that if you don't give the absolute path for the templates in your ini file, it fails. I am gonna try to find a fix for that.

**Comment by byvernault** [comment]
We can probably use the user_home variable and call it: dax_home and all the templates files should be in this folder. People can put their user home folder or an other one. In the code, we can just do:

filepath = os.path.join(self.get_user_home(),  self.get('cluster', 'job_template'))

instead of:

filepath = self.get('cluster', 'job_template')

Or we can just check that if it's ~/ at the beginning of the path given, we change it to os.path.expanduser('~')

or if the path doesn't start with /, join the user_home to the path given to the filename.

I don't know which one should be the best. What do you think?

**Comment by damonms** [comment]
:(.
________________________________

**Comment by damonms** [comment]
I'd prefer to use absolute paths, but if you can find some way for relatives I'll take a look at it
________________________________

**Comment by aplassard** [comment]
Why can't we just run os.path.abspath on all paths that are given?

**Comment by byvernault** [comment]
os.path.abspath actually appends the path were you are running your script
from to the path given so if you don't run it from your home folder, it's
not gonna do what we want.

**Comment by byvernault** [comment]
I found some issues on the branch. I need to go but I will fix them on monday morning and then we can test more this branch. 

Cheers,

Ben

**Comment by damonms** [comment]
Thanks, Ben!



Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by byvernault** [comment]
I updated dax_setup to add the dax_setup_handler class in this executable.

I added a tab completion for path (when people wants to enter the full path or the path for the different files, you can use tab to complete the path). It can be handy. let me know what do you think.

I added as well some code to:
   1) if no value given when there is a default value, it uses the default value.
   2) if a path is asked (like the path for the file templates), if the path doesn't exists, ask again, if value is empty, ask again for the path.

We maybe don't want to have the second point (check if the files exist) and instead just print a line saying that the files doesn't exist yet.

**Comment by damonms** [comment]
Thanks for the updates, Ben!

RE: The last point, maybe we should add something in the config file to be use_grid=True or use_grid=False? I think it should definitely error if the template doesn't exist and they are running on the grid. Thoughts?

Cheers,
Steve
________________________________________

**Comment by damonms** [comment]
Thanks @byvernault for catching the double fields error on my part.

**Comment by byvernault** [comment]
Alright, I think it's ready to be tested now. 

Steve, I really like your branch. It's a pretty cool idea.
Brian, can you test it? I will test it here as well. I am waiting to have my scratch folder set up on the cluster before doing it. 

Cheers,

Ben

**Comment by bud42** [comment]
hello, I'm testing this branch now.

**Comment by bud42** [comment]
Testing is going well. I have a few questions regarding the setup:
Could dax_setup refer to the templates repo?  Maybe suggest downloading the templates for your platform and editing the files before running dax_setup? And should we suggest storing the files somewhere like ~/.dax_templates? The only file I needed to change was cmd_count_nb_jobs.txt.

**Comment by damonms** [comment]
That all sounds like good changes to me! I especially like the hidden home directory. I can easily see myself accidentally blowing away a directory that I wasn't supposed to late at night...

Steve
________________________________________

**Pull request merged**
