### PR TITLE
Added message to contact Administrator for Database error

### PR DESCRIPTION
**Pull request by KarthikMasi**

### CODE REVIEW

**Comment by baxpr** [comment]
Do you think the message can say "possible web server reset needed"? That would be a lot more clear when this happens again in 6 or 12 months - at least to me

**Comment by KarthikMasi** [comment]
I can change it that way. Sounds better to me too.

**Comment by KarthikMasi** [comment]
@baxpr How about now?

**Comment by baxpr** [comment]
@KarthikMasi sounds great to me! @bud42 can we add this to the next release?

**Pull request merged**
