### PR TITLE
Performance

### PR DESCRIPTION
**Pull request by vuiiscci**
Brian,

Can you take a look and merge and update pip if things look ok on your end? I tested and it *appears* to work well.

Thanks,

-Justin

### CODE REVIEW

**Comment by atbenmurray** [comment]
Do you want to go over the changes with me quickly?
Cheers,
Ben

**Comment by bud42** [comment]
Just documenting that we had a skype this week. Ben will be making a few more mods for us to test and then I will merge.

**Comment by bud42** [comment]
@atbenmurray are you ready for this to be merged? I've been testing and it's working great for me.

**Comment by bud42** [comment]
Wait, it seems that only the first session of each subject is being built. I think find_with_pred is not doing what we want here:
https://github.com/VUIIS/dax/blob/ddc22af13e7d3ebddb6ff625d581b8edecf1c622/dax/launcher.py#L672

**Comment by atbenmurray** [comment]
Looking into it

**Comment by bud42** [comment]
Thanks Ben! It's still only building the first session for a subject. Can you try a subject with multiple sessions?

**Comment by atbenmurray** [comment]
Hi Brian, as far as I can tell, it is going over all sessions for each subject. I run dax build as follows:
`build
--project
proj1
/home/ben/git/comic100_dax_config/settings/test.yaml`

**Comment by bud42** [comment]
@atbenmurray thanks for checking! It seems to be an inconsistent problem. I tried a test project with new data and it worked fine. But, with an existing project, it seems to be building the first session twice instead of each of the two sessions. I'll see if I can dig more.

**Comment by bud42** [comment]
@atbenmurray see attached illustration of problem I'm seeing.
[dax_build_problem_2019-05-13.pdf](https://github.com/VUIIS/dax/files/3174583/dax_build_problem_2019-05-13.pdf)

**Comment by atbenmurray** [comment]
That's very useful! I'll look into it

**Pull request merged**
