### PR TITLE
Speed up dax launch

### PR DESCRIPTION
**Pull request by damonms**
I named this one poorly. I had intended on speeding up dax_launch, however it turned into getting Sphinx working... Here's the live URL for this branch: http://dax.readthedocs.org/en/speed_up_dax_launch/

I have it building this branch and master. We can adapt as needed and add a post commit hook so they always autobuild. 

I'm not partial to the css or anything in terms of order (it's all default and looks clean). The search actually works too which is kind of nice. 

Thoughts on merging this?

### CODE REVIEW

**Comment by bud42** [comment]
you deserve a :beer: for this! I'll look through this soon.

**Comment by byvernault** [comment]
Really cool. Thanks Steve for looking into this. You should stop by London for a pint.

**Comment by byvernault** [comment]
Hi Steve,

Great job on using Sphinx for dax. Looks cool.

One question, do you just need to write the docString like:

:param param: definition
:return: object

Should we do :return python list: list of scans for the project/subject/session for example with Sphinx?

Second, I went through the full XnatUtils and this is where they might be some edit to do. I am displaying all the stuff I saw from previous .

186 -> SpiderProcessHandler
188 -> script_name: Basename of the spider ( or full path works as well, it will be removed)
459 -> Clean directory if no error and pdf created
	    :param directory: directory to be cleaned
558 - 585 - 591 - 647 - 689 - 804 - 810 - 979 - 985 - 1008 - 1120 - 1124 - 1129 - 1133 - doc string to write

1158 - 1170 -> replace if the assessor by if the CachedImageAssessor object 

1182 - 1196 - 1243 -> Deprecated method — it’s not deprecated, it’s just using the assessor object directly instead of the cassr. I implemented both because the user might have one and not the other one or vice-versa.

1218 - 1254 - 1860 -> remove previous comments

1364 -> hierarchy 

1637 - 1676 - 3066 -> :param fname: save the file on disk with this value

1942 -> Remove TempDir and put it line 1945 as default. Instead: makes a sub directory prefix_date in the directory specified.

2020 -> The data to upload

2350 -> Entry point

Third, some potential changes for XnatUtils:
Do we still use list_experiments?
Should we rename list_experiment_resoures by list_session_resources?

In AssessorHandler, should we do a select_cassessor to return a cassr object?

Adding a function to get an AssessorHandler by giving project, subject, session, (scan,) prototype.
Cheers,

Ben

P.S: I will check the other files as well.

**Comment by byvernault** [comment]
Hi Steve, 

I edited the XnatUtils to add the missing doc string and remove some double old doc string that were still present in the file under your doc string.

I will edit the other files this morning or later today.

Let me know if something is missing or something is wrong.

Cheers,

Ben

**Comment by byvernault** [comment]
Hi,

I finished editing the main files by adding doc string to the method missing it.
Let me know if you find any without it.

I am gonna check the executables in bin as well.

Btw, Steve, we should probably do a section in the documentation on how to use the executables and use dax in general. Probably, we can add a section on how to write a spiders as well. What do you think?

Cheers,

Ben

**Comment by damonms** [comment]
Thanks for all the additions, Ben!

Yes, I agree we should add both of those. For now I think I'm in favor of merging this PR just to get it into master and then we can update as needed. 

Thoughts @bud42 @byvernault?

Steve

**Comment by byvernault** [comment]
I am good with it.

Ben

**Comment by bud42** [comment]
I wanted to look more thoroughly at some of the other changes in this PR. doing that now.

**Comment by damonms** [comment]
Sounds good!



Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by byvernault** [comment]
The conflicts come from three files: Xnatmirror, tutorials.rst and conf.py (both files are in docs/).

**Comment by bud42** [comment]
I've been running this branch and all looks good. Who wants to merge?

**Comment by damonms** [comment]
I'll merge it

**Pull request merged**
