### PR TITLE
BIDS/XNAT Support

### PR DESCRIPTION
**Pull request by praitayini**
Added the option --bids --bids_dir to Xnatdownload tool. It transfers the data from XNAT hierarchy to a BIDS folder. It works for downloading BIDS compliant sessions. The tool renames files and adds json sidecar (if it is not present). These sessions can be used as inputs to BIDS app. 
(Eg: Xnatdownload -d one_sess/ --p WOODWARD_TCP --sess 113499 -s T1W/3D/TFE,Resting" "State --rs NIFTI --bids --bids_dir bids_dataset/)
BIDSMapping tool is used to create/modify the BIDS datatype, tasktype and repetition time mapping to the series description or scan type of the scans on XNAT. These mapping/rules are present at the project level on XNAT. BIDSMapping --help for detailed information.

### CODE REVIEW

**Comment by baxpr** [comment]
@KarthikMasi I seem to remember we visited that -d / --bids_dir thing before. It's a bit redundant but this was a simple and reasonable way to go. They are actually used differently in the code as I recall.

**Comment by praitayini** [comment]
The code first downloads the data into a XNAT folder and then transfers it to the BIDS folder. That's why we need -d and --bids_dir. Yes, we visited this and it seemed better to go this way.

**Comment by KarthikMasi** [comment]
I am good with that. We could perhaps change the description for the arguments in the "help" section to better assist the user in picking the right options. Could include an example for bids download where we have both -d and --bids_dir called.

**Comment by praitayini** [comment]
Sure @KarthikMasi I can add that

**Comment by praitayini** [comment]
@baxpr @KarthikMasi Thanks for your comments. I add an example for BIDS download to the help. I also add more examples for BIDSMapping. Let me know what you think.

**Comment by baxpr** [comment]
Looks good to me. It is traditional to use e.g. --ud rather than -ud when argument has more than one letter though

**Comment by baxpr** [comment]
Or I guess it would be better to find a short form (single letter) variant that doesn't conflict. Or skip the single letter form altogether.

**Comment by praitayini** [comment]
Thank you. I'm waiting on @bud42 comments

**Pull request merged**
