### PR TITLE
Auto processors

### PR DESCRIPTION
**Pull request by byvernault**
Hi team,

I have been working on creating the autoprocessor to go with the autospider. It's using the YAML format and make it easy to generate a processor for any user. The yaml files are given to the launcher as a new variable. In the init, it will create the processor and add them to the list of processor. I added a generator for a yaml file as well.

News:
  - autoprocessor: processor using a yaml file to define the inputs and command to run
  - dax executable: one executable for all dax scripts. I regrouped all the executable (build, update, upload, test, launch, setup) under one script called dax.
  - dax test: I rewrote the dax test to allow the user to give a processor.py/processor.yaml/module.py/settings.py file directly
  - dax_generator: I moved all the generator into one file to simplify the executable. I kept all the executables that are now deprecated to old_tools. We can think about removing them later on when we are ok with dax/dax_generator.

I have been testing the yaml processor for few days now and it's working so far. There might be some cases that I didn't anticipate. If you find one, contact me.

Let me know if you have any questions,
Kind Regards,
Ben

### CODE REVIEW

**Comment by byvernault** [comment]
@bud42, @damonms  any news on this. 
Did you get time to look at it?

Kind Regards,

**Comment by damonms** [comment]
Can we make these work off of the csv files that the autospider uses?

**Comment by byvernault** [comment]
Hmm, we don't know which inputs are related to XNAT and which one isn't. Also, if it's a resource on scan or assessor. We might be able to produce a first draft of the YAML file by adding all the options to the inputs/default but the user will still need to set the information about XNAT.

**Comment by byvernault** [comment]
@bud42 , I have added the changes that I suggested for Xnatmirror in the issue #152 . If you disagree with those changes, let me know and I will remove them from the PR.

**Comment by bud42** [comment]
Thanks Benjy! testing now

**Comment by jucestain** [comment]
Is there something in the autoprocessor to download individual files (like /project/subject/experiments/assessor/out/resources/files/file) from resources instead of the entire resource itself? I only see:

        assr_tmp = 'xnat:/project/{0}/subject/{1}/experiment/{2}/assessor/{3}/\
resource/{4}'
        scan_tmp = 'xnat:/project/{0}/subject/{1}/experiment/{2}/scan/{3}/\
resource/{4}'

Also how does this interface with the xnat_process_importer/redcap? Do we need to make make an AutoProcessor class and a separate yaml file?

**Pull request merged**
