### PR TITLE
Request to merge PK's branch for XnatToBids fix

### PR DESCRIPTION
**Pull request by lawlessrd**
PK's branch fixes an error in XnatToBids causing it to pull the wrong scans from XNAT. Most of her changes are specific to bids functions, but wanted to make sure the changes in Xnatupload/Xnatdownload are ok.

### CODE REVIEW

**Comment by baxpr** [comment]
@lawlessrd I see that bin/Xnat_tools/Xnatupload is referencing the wrong python -can you fix?

**Comment by baxpr** [comment]
@lawlessrd please also talk to PK about the bond/cuBIDS dependency.

**Comment by lawlessrd** [comment]
Fixed python version, now waiting to hear back from PK.

**Comment by baxpr** [comment]
@bud42 can you take a look at this? Would be great to integrate in the next release if possible - couple of external containers like MRIQC need this bids stuff.

**Pull request merged**
