### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by praitayini**
added fpdf package - it is required for the bids job template

### CODE REVIEW

**Comment by baxpr** [comment]
Yeah that seems worth it... Need to coordinate with Brian on releases

**Comment by baxpr** [comment]
@bud42

**Comment by bud42** [comment]
Looks like fpdf is no longer active, but there's an active fork called fpdf2. Any thoughts on which one we should use?

**Comment by praitayini** [comment]
We can use fpdf2. It is newer and I dont have to change much in my code either for it - only the line spacing.

**Pull request merged**
