### PR TITLE
Regex

### PR DESCRIPTION
**Pull request by byvernault**
Hello guys,

This is branch is ready to be pushed. I fix one bug and added two options to XnatSwitchProcessStatus that aren't too much related to regex. Sorry about that.

Bug fix:
1) I fixed some issues on the pdf generator for spiders.py function. I swap the dimension of the images before displaying them to properly see axial/cor/sag on the PDF page.

Features:
1) I added some semi regex and full regex to filter the list when using Xnat_tools. There is a function in XnatUtils where you can filter a list of the dictionary that we retrieve from XNAT with REST API.
2) I implemented --rerun/--restart in XnatSwitchProcessStatus. I am sure Brian is going to like this. --rerun will act like -s NEED_TO_RUN -f JOB_FAILED -d: it will change the failed jobs to NEED_TO_RUN and delete the resources. You can call it like:
XnatSwitchProcessStatus -p XXX -t Multi_Atlas* --rerun
For restart, it's not checking the formerstatus, it's restarting everything. For example if you want to restart a specific assessor:
XnatSwitchProcessStatus -p XXX -a XXX-x-XXX-x-XXX-x-XXX --restart

I have been using this branch for some times now and it's working well. Let me know if you have any questions,

Kind Regards

### CODE REVIEW

**Comment by bud42** [comment]
Fantastic! Trying it now.

**Comment by bud42** [comment]
Ok, the rerun and restart flags with XnatSwitchProcessStatus are working great. Awesome!

I've moved on to Xnatdownload and it seems the "--sess" flag is broken. @byvernault is it working for you?

**Comment by byvernault** [comment]
I will check tomorrow morning. 

Thanks for testing.

Ben

**Comment by byvernault** [comment]
Hey Brian,

What about now? Could you try it again?

Thanks for looking into the push request.

Kind Regards,

Ben

**Comment by byvernault** [comment]
I might have found an other issue on the pdf generator. Let me check it before pushing.

Sorry for the delay.

**Comment by byvernault** [comment]
Ok good to go. Did you find anything else?

**Comment by bud42** [comment]
Working great. Thanks Ben!

**Pull request merged**
