### PR TITLE
Adding ALL DAX Documentation

### PR DESCRIPTION
**Pull request by duettwe**
Uploading ALL DAX Documentation. Some of this may be incorrect, but the pages have been built out based on the new site (where I'm going to remove this information). I'm adding it here so we can all edit and make changes.

### CODE REVIEW

**Comment by baxpr** [comment]
Wil - FYI you can make a new push to the same branch and the existing PR will update. No need to close and open a new one. I'll go through this when I get a change and make some edits.

**Comment by baxpr** [comment]
@duettwe Couple questions - right now we have some spider specific docs in here:

cci_process_with_xnat.rst
containerized_image_processing_pipelines.rst

However, these are not part of DAX. What's the big picture plan for documenting specific spiders?

And this is not DAX:

sending_dicom_to_vanderbilt_xnat.rst

Where should it go?

**Comment by duettwe** [comment]
Let's just take those out and I'll leave them on the new site for now. We have a spider specific section on the new site, so those can go there.

**Comment by baxpr** [comment]
Sounds good - done

**Comment by baxpr** [comment]
Where is the up-to-date dax config process? We should have it written down somewhere, configuring_dax_on_accre.rst  is not correct

**Comment by baxpr** [comment]
Same for dax_command_line_tools.rst

**Comment by duettwe** [comment]
It should be correct in the installing_dax_in_a_virtual_environment.rst page. I also missed a page entirely that has the correct information on it.

**Comment by baxpr** [comment]
Same for dax_installation.rst - it is calling for python 2 which is wrong. Where is the up to date process?

**Comment by baxpr** [comment]
Do you think it's safe to just delete these older docs?

configuring_dax_on_accre.rst
dax_installation.rst

**Comment by baxpr** [comment]
"Alternative Installation (non-pip)" instructions in installing_dax_in_a_virtual_environment.rst are not correct. Does anybody have correct instructions? Otherwise I'll just delete that section

**Comment by duettwe** [comment]
They seem to cover the same thing. The page that I mentioned missing earlier is that I need to update dax_installation.rst, so lets leave that one for now and I'll update it with the new info.

**Comment by baxpr** [comment]
download_data_from_xnat.rst is also xnat-oriented, not DAX. @duettwe can you move this one also to wherever the other xnat stuff is?

**Comment by duettwe** [comment]
Sure!

**Comment by baxpr** [comment]
In manage_a_project.rst - can you confirm that the NEED_TO_RUN status actually has this effect? Previously we were setting to NEED_INPUTS

**Comment by baxpr** [comment]
upload_data_to_xnat.rst also needs to move to the xnat place

**Comment by baxpr** [comment]
Ok, I've been through the whole dir and done what I can. I deleted stuff pretty aggressively but I flagged it all here. @bud42 maybe you could take a look through this issue thread and make sure I didn't do anything dumb?

**Comment by bud42** [comment]
I made a few minor edits. Also, I'm thinking these shouldn't be in DAX docs:
modules.rst
dax_ldax_sop_accre_production_accounts.rst

Is there a better place for these?

**Comment by duettwe** [comment]
I can keep them on the new website for now and remove them here.

**Comment by duettwe** [comment]
I removed the files mentioned, leaving them on the new website:

modules.rst
dax_ldax_sop_accre_production_accounts.rst

Also removed some image files that were related to the pages we've removed.

**Comment by duettwe** [comment]
Is there anything else needed here or can we merge? Thanks for the help so far!

**Comment by baxpr** [comment]
I'm happy! @bud42 do you need anything special with regard to branches/tags etc?

**Comment by bud42** [comment]
Looks good! Merging.

**Pull request merged**
