### PR TITLE
Adding a try except around a problematic part for the MONROE project

### PR DESCRIPTION
**Pull request by damonms**
I added a try catch around a problematic part of list_sessions that sometimes gets an index error. Rather than error I have it set things to UNK.

### CODE REVIEW

**Comment by byvernault** [comment]
Looks alright. @bud42 ?

**Comment by bud42** [comment]
Fine with me. It would be nice to know what's causing the problem.

**Comment by byvernault** [comment]
@damonms , Any idea why it does that??

**Comment by byvernault** [comment]
I think we can close this since you add it, right?

Cheers,

**Pull request closed without merging**
