### PR TITLE
Editing dax_setup to allow user to use default settings for Xnat_tools/Freesurfer_tools.

### PR DESCRIPTION
**Pull request by byvernault**
Hi guys,

This pull request is to fix the issue 73 raised recently about dax_setup being to complicated for only Xnat_tools/Freesurfer_tools usage. I added to dax_setup two things:

1) XNAT credentials. If they are not set in an ~/.xnat_profile on the computer, it will ask the user for the credentials and saved them in this file and add to their .bash_profile: . ~/.xnat_profile. If bash_profile doesn't exist, it will try to search for .bashrc or .profile and set this in any of those files.

2) Added a first question to ask the user if he wants to use the default settings for tools purpose. See below:

########## DAX_SETUP ##########
Script to setup the ~/.dax_settings.ini files for your dax installation.

Do you want to select default settings adapted for Xnat_tools/Freesurfer_tools use only? [yes/no]y
Warning: Not recommended if you want to use dax_tools.
        Read the wiki for more information on dax_setup and setting dax for cluster use.
         Wiki: https://github.com/VUIIS/dax/wiki/DAX-Set-up
Warning: REDCap not used. Setting the dax_manager to null.

0 error(s) -- dax_setup done.
########## END ##########

And the user should be good to go to run all tools. It might not work properly for dax_tools since it's using by default the SGE (1) templates. 

What do you think?

Kind Regards,

Ben

### CODE REVIEW

**Comment by bud42** [comment]
Works for me.

**Comment by damonms** [comment]
Same. Thanks for updating the wiki. Does this also fix the sphinx issue since there is no default settings file?
________________________________

**Comment by byvernault** [comment]
I didn't look into that. 

Ben

**Comment by byvernault** [comment]
We can definitely add this into this request and try to get sphinx to work again. I don't have time right now to look to much into it.

**Comment by damonms** [comment]
OK, I'll take a stab at it. I'll probably just have it put in a blank file on setup which will pass through
________________________________

**Pull request merged**
