### PR TITLE
Added inputs field to some assessor retrievals

### PR DESCRIPTION
**Pull request by baxpr**
Let's not be in a hurry to merge this, someone else should verify that it makes sense. But I have updated get_project_assessors and list_project_assessors in XnatUtils.py to return the inputs field of genproc assessors.

### CODE REVIEW

**Comment by bud42** [comment]
Trying this now. The inputs field works great. Do you want the report tool to be executable by just typing Xnatreport_assessor, like the other tools in bin?

**Comment by bud42** [comment]
Should we go ahead and decode the quotes and parse the json so that assr['inputs'] is a dictionary?

**Comment by baxpr** [comment]
Probably? I'm not quite sure of the implications. I did feel pretty silly using a string replace to get rid of the "&quot;" stuff though

**Comment by atbenmurray** [comment]
> Probably? I'm not quite sure of the implications. I did feel pretty silly using a string replace to get rid of the "&quot;" stuff though

You can make use of decode_url_json_string in dax/utilities.py

**Pull request merged**
