### PR TITLE
Diskq

### PR DESCRIPTION
**Pull request by bud42**
Trying this again after merging recent changes from master...

Hello! This branch adds an alternate way to manage tasks/jobs using files on disk instead of XNAT. The goal is to minimize the interactions with XNAT to track the state of open jobs. When a new task is ready, the batch (or PBS) file is immediately written to disk. From that point until upload, XNAT is not needed.

In addition, this allows DAX to run in a situation where the only communication between XNAT and the cluster is via a shared filesystem. On the system with access to XNAT, you'd set the launcher_type to diskq-xnat and only run dax_build and dax_upload. Then on the system with access to the cluster, you would set the launcher_type to diskq-cluster and only run dax_update_tasks and dax_launch. This should be helpful to @MattVUIIS. Note that we still need to implement a way to pre-download inputs.

And lastly, a modification to the behavior of Processors is included. The new function build_cmds() can replace the pair of existing functions has_inputs() and get_cmds(). When build_cmds() is called it should either return the commands to be run in the Batch or raise an exception. The exception should either be NeedInputsException or NoDataException. The contents of the exception should be the reason. This in effect performs the same function as has_inputs(). We are basically combining has_inputs() and get_cmds() in a way that asks for forgiveness rather than permission. Note that the old way is still supported if build_cmds() is not implemented by a processor.

P.S. 
While coding this, I realized that some major refactoring would be beneficial. What we have now has evolved into a bit of a mess. I decided to leave the mess and integrate this functionality into the existing structure, so it is easier to switch between the old way and this new way.

### CODE REVIEW

**Comment by damonms** [comment]
I love this. Going to put it up on the data project account. I suspect this will greatly help with "odd hour sadness"

**Comment by damonms** [comment]
I think we've worked out the bugs on this, right?

**Comment by bud42** [comment]
I think we're ready to merge this. I'll work on the conflicts now.

**Comment by bud42** [comment]
Ok, we're all set. Anybody wanna merge?

**Pull request merged**
