### PR TITLE
Update index file; includes new pages and new install

### PR DESCRIPTION
**Pull request by duettwe**
I believe this was done correctly. If not, let me know.

### CODE REVIEW

**Comment by duettwe** [comment]
Works for me!

**Comment by baxpr** [comment]
It didn't work right :)

**Comment by baxpr** [comment]
...I was looking in the wrong place! Never mind. Please check for yourself, guarantee you understand better than I do what was supposed to happen

**Comment by duettwe** [comment]
Some things seem to be right and others not. So it sort of worked right.

**Pull request merged**
