### PR TITLE
New options for Xnat tools

### PR DESCRIPTION
**Pull request by byvernault**
Hi everyone,

I started this branch to add to all the Xnat tools the two options:
 --host to be able to specify XNAT host when calling the executables
 -u/--username to specify the username on the XNAT and it will ask for the password

In fact, I went farther and rewrite part of the code to make it cleaner and I did that for all the tools. It should not have changed the tools but I think it might be better to try them before pushing the request.

I added as well some code to check for the datatypes installed on the XNAT used with dax. We have several XNAT instances installed at UCL and we need to be able to switch between one and the other and some doesn't have the dax datatypes. It's the reason behind this point and the first one as well.

I am testing it on the cluster but it's not yet developed like you have at Vanderbilt so if you could test it out, that will be great. I added docstring to dax_manager.

Let me know if you have any question,

Cheers,

Ben

### CODE REVIEW

**Comment by bud42** [comment]
Dude, this is a lot of changes

**Comment by byvernault** [comment]
Yes sorry, I got really into this.

In fact, the changes should not  change anything to the scripts. :)

**Comment by aplassard** [comment]
Is there more than one commit for this? I don't think this should be merged
without commits that are easier to digest.

**Comment by byvernault** [comment]
Let me change this and make different commit between cleaning code and
actually changes.
It will be easier.

I pushed everything this morning but I should have divided it.

**Comment by byvernault** [comment]
Let me go back before the commit and do it in steps.

**Comment by byvernault** [comment]
Closing this to reopen it later today.

**Pull request closed without merging**
