### PR TITLE
Update qcstatus list

### PR DESCRIPTION
**Pull request by bud42**

### CODE REVIEW

**Comment by byvernault** [comment]
Hi Brian,

Thanks for doing this.

Should we change Needs QA to Needs QC?
Should we also change the fs_proc.jar file for the status?

Cheers,

Ben

**Comment by byvernault** [comment]
One more thing Brian,

I was thinking that we could add Do not run or something like that for the qc status that means that it should not run anymore because of errors or bad scans. This could then trigger the Job status in dax to set it up to DO_NOT_RUN since we have no way on XNAT for the user to edit the JOB STATUS to DO_NOT_RUN. Something like Rerun but when it shouldn't run in the future.

We can probably find a better qc status than should not run. :)

Ben

**Comment by bud42** [comment]
@byvernault 

Here's the list:
Passed
Good
OK
Poor
Do Not Run
Rerun
Needs QA
Needs Edits
Bad
Failed

**Comment by BennettLandman** [comment]
Looks good to me

Sent from my Android phone

-----Original Message-----

**Comment by byvernault** [comment]
Should we switch Needs QA to Needs QC?

Most people in London use QC and not QA.

Ben

**Comment by damonms** [comment]
I really don't want to change this. We have a lot of code that looks for QA already
________________________________________

**Comment by BennettLandman** [comment]
Let's allow both

Sent from my Android phone

-----Original Message-----

**Comment by byvernault** [comment]
Or we could do Needs Review :)

I am trying to fix the issue with setting the username when using the assessor to edit the status. When we got this sort out, I think we can push this request.

Cheers,

Ben

**Pull request merged**
